### ISSUE TITLE
md-autocomplete vs. paper-autocomplete

### ISSUE THREAD

**Issue by dandv** [ellipticaljs/paper-autocomplete#1]
What are the differences between https://customelements.io/EllipticalElements/md-autocomplete/
and
https://customelements.io/ellipticaljs/paper-autocomplete/ ?

The READMEs look almost identical and they both point to this repo's demo.

**Comment by tachyon1337** [comment]
As of now, they're the same.  I migrated this repo to another organization for custom element repos only and changed the prefix from "paper" to "md" to be consistent with the other material design element names. I haven't had time to do github pages for md-autocomplete so I temporarily pointed a link to the "paper" one that I had up. 

However, I have another unpublished autocomplete component(that works more like the one at facebook) that I might end up putting under md-autocomplete(v2.x.x). Its why I didn't do a simple move and rename. If I choose a different name for the unpublished component(when i publish it), then I will deprecate the paper-autocomplete repo.
