### ISSUE TITLE
Expose the invalid property of paper-input

### ISSUE THREAD

**Issue by miztroh-zz** [ellipticaljs/paper-autocomplete#112]
The `invalid` property of the underlying `paper-input` needs to exposed to `paper-autocomplete`.  This will address a variety of issues, including #50.  A simple example is needing to be able to reset a form, clearing any invalid states.  For a `paper-input` (or `paper-dropdown-menu`, etc.), all you have to do is set the element's `invalid` property to `false`.  For `paper-autocomplete`, I'm having to set `element.$.autocompleteInput.invalid = false`.  I shouldn't have to know anything about the internals of your element in order to have this functionality.  Seems like this issue is low hanging fruit that could easily be resolved.  Thanks in advance!

**Comment by teddyward** [comment]
This would be a huge help for us!

**Comment by jhuesos** [comment]
Last week I released a new version that exposes the invalid property:

https://github.com/ellipticaljs/paper-autocomplete/pull/111

v3.7.0 of this component has this fix.

Is that not what you need? If the answer is no then why?

Fixed by #111
