### ISSUE TITLE
How to control suggestion list width

### ISSUE THREAD

**Issue by leifneve** [ellipticaljs/paper-autocomplete#118]
How can I set the suggestion list width to be whatever the widest suggestion item is rather than the default (which appears to be 100%)?

**Comment by leifneve** [comment]
Update: Once I figured out how to apply the --suggestions-wrapper mixin, I was good!

**Comment by jhuesos** [comment]
So if it is not a problem anymore, can you close the issue? Thanks

**Comment by leifneve** [comment]
Update: Once I figured out how to apply the --suggestions-wrapper mixin, I was good!
