### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by kito99** [ellipticaljs/paper-autocomplete#14]
I noticed the docs are out-of-date with the most recent release (took me a long time to figure that out!) The most important thing is  event separator; in the release it still uses "."

Can you create a new release?

**Comment by tachyon1337** [comment]
@kito99  
Were you installing via bower? I verified that `bower install paper-autocomplete` was installing v1.1.1 instead of v1.1.2. So I pushed a version update to v1.1.3 and verified bower is bringing down the latest version now.
