### ISSUE TITLE
Expose a method for closing the suggestions list programmatically

### ISSUE THREAD

**Issue by kito99** [ellipticaljs/paper-autocomplete#16]
Right now, the best way to do this seems to be calling _onBlur(), which is a private method. For example, I need to close the suggestions list whenever the user presses Enter.

**Comment by tachyon1337** [comment]
I've now added a public method `hideSuggestions()`.

I'll keep this issue open as reminder to update the docs with the new method when I have the time.  After updating the docs, I will then close this out.

**Comment by jhuesos** [comment]
This new api method now is documented so this issue can be closed.
