### ISSUE TITLE
Two paper-autocompletes on the same page

### ISSUE THREAD

**Issue by StokeMasterJack** [ellipticaljs/paper-autocomplete#20]
I have two paper-autocompletes on the same page. The first one worked great until I added the second one. Now, the dropdown for paper-autocomplete#2 shows up attached to the bottom of paper-autocomplete#1.

**Comment by StokeMasterJack** [comment]
Never mind. This was a bug in my code.

**Comment by tachyon1337** [comment]
Ok...btw, the demo page has two autocomplete components...one pulling from a hard-coded states' array and the other dynamically querying the github user api.
