### ISSUE TITLE
Make component accessible (ARIA)

### ISSUE THREAD

**Issue by jhuesos** [ellipticaljs/paper-autocomplete#23]
At this moment the component is not accessible. It does not follow rules defined in: https://www.w3.org/TR/wai-aria/

It is highly possible that we will be using this component in my current company, so I will try to make a pull request with the necessary changes.

**Comment by tachyon1337** [comment]
@jhuesos 

Yeah, ARIA support for web components is usually a low priority issue for me. I will certainly merge any pull requests that address the issue.

Thanx

**Comment by jhuesos** [comment]
If my company finally decide to go with this component, it will be even possible to run my fix through some accessibility experts. I will create a Pull Request once I am done, most likely this week.

**Comment by jhuesos** [comment]
Closed by #29
