### ISSUE TITLE
Double X button to clear input field in IE/EDGE

### ISSUE THREAD

**Issue by jhuesos** [ellipticaljs/paper-autocomplete#24]
Because Internet Explorer (at least version 11) and EDGE add a X button by default to clear the content of an input field.

![screen shot 2016-10-08 at 12 21 12](https://cloud.githubusercontent.com/assets/339609/19212450/be0e510c-8d51-11e6-96cc-fe6de410df29.png)

**Comment by jhuesos** [comment]
In this case I am not sure it should be done: hide the native X button? Or maybe if IE/EDGE, ignore the clear content option and never show the custom X clear button?

**Comment by tachyon1337** [comment]
hide the native clear button...

I believe IE/Edge has a pseudo class for the clear button on input elements
`::ms-clear`

**Comment by jhuesos** [comment]
Fixed in v2.5.0
