### ISSUE TITLE
Support custom item result templates

### ISSUE THREAD

**Issue by jhuesos** [ellipticaljs/paper-autocomplete#27]
I think it would be good to be able to provide custom templates for search results. In many auto-suggest situation, apart from simple text, you maybe would like to add a custom icon next to the results, or show multiple lines of text.

Something like:

<img width="662" alt="screen shot 2016-10-13 at 17 24 45" src="https://cloud.githubusercontent.com/assets/339609/19355246/005bbccc-916a-11e6-9dff-7d33ddb64ac6.png">

**Comment by tachyon1337** [comment]
@jhuesos 
That's similar the facebook-like one I've developed, which supports templating in the light DOM. It would be a separate element.

**Comment by jhuesos** [comment]
@tachyon1337 any chance you can give more details about the implementation? what is it missing to publish?

**Comment by tachyon1337** [comment]
@jhuesos 

it uses my ellipticaljs custom behaviors, including dustjs for the light dom templating, service injection...stuff that I find convenient b/c i wrote it...but there's no docs. Does polymer even allow light dom item templating inside the element? In any event, i didn't think polymer 1.0 was stable enough nor sufficiently documented to try it the pure ploymer way. I was going to wait to 2.0 to take a stab at it using polymer templating in the element's light dom.

**Comment by jhuesos** [comment]
Close by #39
