### ISSUE TITLE
populate of suggestions as soon as user clicks the component

### ISSUE THREAD

**Issue by basav1989** [ellipticaljs/paper-autocomplete#28]
I was trying out paper-autocomplete to provide a list of suggestions.
But I have a use-case where as soon as the cursor is placed on component, all the suggestions need to be displayed and as the user types, the updated suggestions need to be shown.

Right now, the `_suggested` array is only populated only once user enters a key.

I can make the changes to make this work, but I wanted to clarify that I am not missing on any existing feature.

Do we have a way to get this feature working without modifying existing paper-autocomplete code ??

**Comment by jhuesos** [comment]
No, this is not possible at this moment. I will look into it. At this moment we might be introducing a new feature that might introduce some significant code changes. I will come back to you on this in a week time.

**Comment by Petermo** [comment]
Hi @jhuesos, I was wondering if you might have any update on this specific feature as I'd like it to be present as well.
@basav1989, what was your workaround to get this working?

**Comment by basav1989** [comment]
@Petermo 
set minLength property to 0 and source array(.source = [suggestions];) .

donot remember what other changes i made to get it working, let me know if the above changes donot get it working.

I have changes locally, will upload them if above changes donot get it working.

**Comment by jhuesos** [comment]
I will try to look into this issue and create the feature. It should be possible. I was on holidays and pretty busy at work. And today I finally updated the demo pages and published in webcomponent.org, which were issues that were really urgent as well. I will keep you posted.

Latest demos/docs are finally online: [https://ellipticaljs.github.io/paper-autocomplete/components/paper-autocomplete/](https://ellipticaljs.github.io/paper-autocomplete/components/paper-autocomplete/) :)

**Comment by jhuesos** [comment]
I have spent 5 mins thinking about this problem and then I realized that introducing this change will change the current behavior. 

The way it works now is when you focus in the input field, even if the length of the current value is longer than min-length, we do not show suggestions popup right away. Use must make a change in the value so the suggestions are displayed.

This is not how it would behave if we do show results at the moment the user focus in the input field when the minLength is set to 0.

Maybe we should change the autocomplete component to always show the results whenever user focus and value >= minLength. 

I don't want to introduce an inconsistency in the User Experience of the component only for minLength. So I need to do a little research.

What do you guys think?

**Comment by SPessall** [comment]
Maybe I am missing something, but this issue seems to have been already resolved. At least in our case this worked with adding the _show-results-on-focus_ property and setting _min-length=0_.

Only the documentation does not seem to be up to date regarding this issue.

**Comment by jhuesos** [comment]
@SPessall is right, you can already achieve this setting `show-results-on-focus` and `min-length="0"`. I will close this issue and update documentation. Cheers
