### ISSUE TITLE
To what extent do arrays of strings work, instead of text/value objects?

### ISSUE THREAD

**Issue by dandv** [ellipticaljs/paper-autocomplete#3]
This is re. the comment at the bottom of the docs,

> The current 1.0.xx version only supports binding(locally or remotely) with object arrays

I passed `inputLocal.source=['aa', 'bb']` and the autocomplete displayed the filtered results.

**Comment by tachyon1337** [comment]
yeah, that statement is no longer valid. The component internally remaps the passed array to the template  binding array(which will be array of objects w/ a text and value properties). The passed array can be a simple array of strings. There are now two public properties, textProperty and valueProperty. that can be declaratively set in the element attributes that allow one to bind an arbitrary object array. E.g.

``` html
<paper-autocomplete text-property="userName" value-property="id"></paper-autocomplete>

```

That being said, the public method getOption and the public event autocomplete.selected  do return the selected item as an object with text/value props.
