### ISSUE TITLE
Show input box border

### ISSUE THREAD

**Issue by StokeMasterJack** [ellipticaljs/paper-autocomplete#32]
I am using this widget in an app that is not ready for a complete switch to the paper look and feel. So I would like to style the paper-autocomplete to look more like a conventional text input. Is this possible?

**Comment by jhuesos** [comment]
I am afraid at this moment is not possible. We would have to expose more mixins so you could achieve that. Is it possible to see any screenshot or ellaborate in how are you planning to change the look and feel?

That would help to decide how do we need to change the component to support what you need.

**Comment by kito99** [comment]
You may want to consider adding a "light" version of the component with a configurable input field, like Vaadin does with its elements.

**Comment by jhuesos** [comment]
Actually @kito99 I am going to release this week a new version with what I think you are asking: I am splitting this component in two, so you can add the pop-autosuggest part with any input field.

I am planning to finish the new version this week, but you can checkout this branch: https://github.com/ellipticaljs/paper-autocomplete/tree/feature/separate-popup

After this change is pushed, you will be able to do someting like:

```html
        <div class="autocomplete-wrapper">
          <paper-input id="myInput" label="Select State"></paper-input>

          <paper-autocomplete-suggestions
            for="myInput"
            source="[[accounts]]"></paper-autocomplete-suggestions>
        </div>
```

**Comment by jhuesos** [comment]
You can now use paper-autocomplete with any input field (with version **v2.1.1**). Please clone the repository to see examples of this. The new component is called: paper-autocomplete-suggestions and there is documentation and demos for it.

I will be working on updating the demos/documentation page because it is obsolete.

**Comment by jhuesos** [comment]
Use version **2.1.1**. 

2.1.0 was not tagged correctly. Sorry for that
