### ISSUE TITLE
Change clear button visibility and behavior. 

### ISSUE THREAD

**Issue by jhuesos** [ellipticaljs/paper-autocomplete#37]
At this moment, the reset button is only displayed when:
- you focus in the input field
- and you type at least one character or you make a change

In my opinion, the behavior I would expect is the one you can see in the autocomplete component from Angular material:

https://material.angularjs.org/latest/demo/autocomplete

But it would be good to see the opinions of other users of the component. So please do.

**Comment by tachyon1337** [comment]
To me, they behave similarly, other than pressing the reset button in the angular example doesn't close the dropdown, it just resets the data.

**Comment by jhuesos** [comment]
This has been changed and this issue is obsolete
