### ISSUE TITLE
Fixed demo pages so they work with IE/Edge

### ISSUE THREAD

**Issue by jhuesos** [ellipticaljs/paper-autocomplete#42]
At this moment, some of the demos in the demo page are not working in IE/Edge. They do not work because something strange is happening when using in combination with demo-snippet element.

I haven't been able to figure out why, so if someone can help on this one, I would be very happy and thankful :)

Please, take a look to my question in StackOverflow. It contains a plunkr to reproduce the issue:

http://stackoverflow.com/questions/39915765/element-inside-demo-snippet-is-not-cloned-projected-properly-only-in-ie11

**Comment by Link2Twenty** [comment]
Works for me on edge and IE. The remote stuff doesn't work, give the error

> BAD REQUEST - The request could not be processed by the server due to invalid syntax https://user-content-dot-custom-elements.appspot.com/ellipticaljs/paper-autocomplete/v2.3.1/Elliptical-micro/Elliptical-micro.html

Though it's not working for me in chrome either.

I was looking at the demo here
https://www.webcomponents.org/element/ellipticaljs/paper-autocomplete/demo/demo/index.html

**Comment by jhuesos** [comment]
This has been fixed
