### ISSUE TITLE
Show all results instead of matches

### ISSUE THREAD

**Issue by jaruba** [ellipticaljs/paper-autocomplete#6]
Is there any way to show the entire array of results instead of just the ones that include the input string?

**Comment by jaruba** [comment]
Nvm, I checked the code and realized that `remote-source="true"` doesn't filter the results, seems to be exactly what I need.

Great job, awesome component. :)

**Comment by tachyon1337** [comment]
yeah, `remote-source="true"` leaves it up to the developer to generate a result set to pass to the component based on the user input. One of the reasons I included it, apart from the obvious one of  fetching remote data on the fly.
