### ISSUE TITLE
Autocomplete dropdown shown briefly when full input matches

### ISSUE THREAD

**Issue by vinguyen2011** [ellipticaljs/paper-autocomplete#61]
When full input matches and user press Tab to focus on the input, the drop down shows briefly. Maybe we should increase the time or don't show the dropdown.

**Comment by jhuesos** [comment]
Hi, sorry I am not fully sure if I understand the issue. Can you add detail step to reproduce it? A video maybe?

**Comment by jhuesos** [comment]
I am closing this one because of lack of activity. Please feel free to reopen the issue if you have more information or you still have this problem
