### ISSUE TITLE
paper-autocomplete items not visible due to css

### ISSUE THREAD

**Issue by sankarbalu1** [ellipticaljs/paper-autocomplete#64]
I am facing an issue of listing the items in paper-autocomplete.

![capture](https://cloud.githubusercontent.com/assets/26590731/24184041/e81b5d4c-0ef1-11e7-998a-a1e573d426b8.PNG)
![capture2](https://cloud.githubusercontent.com/assets/26590731/24184046/ed51afe6-0ef1-11e7-9d1a-c5a2b870342a.PNG)

`<paper-autocomplete source="{{ _usageMetricList }}" selected="{{ metric }}" value="{{ mName }}" attr-for-value="metricName" attr-for-label="metricName" required auto-validate class="flex">
              <paper-input label="[[ webL10n(l10n, 'targeting.usageMetric') ]]" error-messages="[[ errorMessages ]]" class="flex"></paper-input>
            </paper-autocomplete>`

if I change the z-index of iron-dropdown it will fit on the screen.Can anyone help me on this issue?

**Comment by jhuesos** [comment]
Let me see if I understand it, the dropdown is not visible and only if you increase the z-index it works? Could you provide a plunkrc, jsbin or equivalent where I can reproduce the issue? Thanks

**Comment by sankarbalu1** [comment]
Thanks jhuesos for your reply.I got a fix for this issue.Yes when I inspect on the browser, I found that the items are fit in the screen once change the z-index.The fix which I applied for this issue is that there was a custom property(--paper-autocomplete-dropdown) specified in the iron-dropdown style.I gave margin for this.Now its fitting on the screen.

`--paper-autocomplete-dropdown: {
    margin-top: 6em;
  }`

**Comment by jhuesos** [comment]
So is it fix now? Should I close this issue? Do you still need a change in the component should be done?

**Comment by sankarbalu1** [comment]
Yes jhuesos.It's fixed now.You can close the bug.Thanks for your help.

**Comment by jhuesos** [comment]
You are very welcome.
