### ISSUE TITLE
Empty result area for arbitrary objects

### ISSUE THREAD

**Issue by TakhirMamirov** [ellipticaljs/paper-autocomplete#66]
I have the following configuration:
```
<paper-input>...</paper-input>
<paper-autocomplete-suggestions id="myid" for="state"
          source="[[states]]" text-property="statename" value-property="value">
</paper-autocomplete-suggestions>
```
and the source defined as:

```
[    { "statename": "Alabama", "value": "AL" },
     { "statename": "Alaska", "value": "AK" },
     { "statename": "American Samoa", "value": "AS" },
     { "statename": "Arizona", "value": "AZ" },
     { "statename": "Arkansas", "value": "AR" }   ];
```
And when I type in the state name, the empty suggestions container is shown (for the resulted amount of options). Notice I set the text-property and value-property explicitly, following the tutorial. This is for example, while my objects are usually more complex.

When I have objects like {text, value}, everything works, but I don't want to all the time convert my source to such representation. I would rather want to use arbitrary objects and define the text and value properties.

**Comment by jhuesos** [comment]
Yes, this looks like bug. The main purpose of the textProperty and ValueProperty is to don't have to transform the values. I will take a look.

**Comment by bdekk** [comment]
It seems that this issue still persists. Is the a timeline for this bug? Next to that, thank you for this component. I am using polymer 2.0 and version 3.3.0 of autocomplete.
