### ISSUE TITLE
autocomplete-reset-blur event is not working

### ISSUE THREAD

**Issue by orenagiv** [ellipticaljs/paper-autocomplete#67]
Hey,

The event 'autocomplete-reset-blur' is not working.
Looking at the code - the correct name of the event is 'autocomplete-reset'.

So when using the following - the event is fired properly upon "clear":
`autocomplete.addEventListener('autocomplete-reset', function() {
    // Do something
});`

**Comment by jhuesos** [comment]
Hey, first of all, thanks for letting us know about this. You are right, the events described in the documentation haven't worked in a little white.

I am fixing the code to follow the API, so I will be triggering the event name: `autocomplete-reset-blur`

**Comment by jhuesos** [comment]
`v2.5.2` contains the fix. Thanks again for letting us know about this problem

**Comment by orenagiv** [comment]
Thanks!

**Comment by hariprasadiit** [comment]
`v3.0.0` has this issue. till `v2.6.1` it's been fixed, but reset code changes seem to introduce it again.

`paper-autocomplete` is firing `reset` event, but `reset-blur` is documented.

**Comment by jhuesos** [comment]
I will reopen it until I release the new version. Sorry for the spam

**Comment by jhuesos** [comment]
Fixed in version `3.0.1`. Thanks again for telling me about this regression.
