### ISSUE TITLE
Pressing enter key when no suggestions are selected prints errors on console

### ISSUE THREAD

**Issue by alejost848** [ellipticaljs/paper-autocomplete#7]
I found that if you press the enter key without typing anything on the input prints `this._suggestions is undefined` on console. Also, if you start typing and press enter then `selectedOption is undefined` which also happens once you have selected a suggestion and press enter again.

I was doing some testing and I think this code on the _keyenter function fixes the unwanted prints.

``` javascript
_keyenter:function(){
  if(this.$.suggestionsWrapper.style.display == 'block' && this._currentIndex > -1){
    var index=this._currentIndex;
    this._selection(index);
  }
}
```

I can do a PR for that if it helps, or maybe there's a different solution.
Thanks for making this element, it's great!

**Comment by tachyon1337** [comment]
alejost848:

submit a pull request...and i'll merge it

thanx

**Comment by tachyon1337** [comment]
merged the pull request..closing issue
