### ISSUE TITLE
2.0-preview _clearSuggestion not working on Firefox

### ISSUE THREAD

**Issue by Zecat** [ellipticaljs/paper-autocomplete#74]
I'm calling sevral times `suggestions()` from `<paper-autocomplete>` to refresh the suggestions and realize the `_clearSuggestion` from paper-autocomplete-suggestion` isn't removing the "suggestions nodes" (Firefox + Polymer 2).

On this line : https://github.com/ellipticaljs/paper-autocomplete/blob/2.0-preview/paper-autocomplete-suggestions.html#L546
`children[0]` always references the first child on Firefox.

**Comment by jhuesos** [comment]
Fixed by #75
