### ISSUE TITLE
Focus locked in the element - Polymer 2

### ISSUE THREAD

**Issue by Zecat** [ellipticaljs/paper-autocomplete#76]
On Polymer 2, once the element is focused, you can not exit it by pressing the TAB key.

The input is focused, then the show clear button is focused, then the input is focused, then the show clear button etc...

The issue is gone by setting `disable-show-clear` attribute.

**Comment by jhuesos** [comment]
I can also reproduce it at least with Chrome in Polymer 2.x. I don't know why this is happening so I will look into it. Do you have any suggestions?

And thanks for letting us know about this issue

**Comment by jhuesos** [comment]
Just tried quickly try to reproduce it with the following code:
```html
<paper-input value={{value}}>
   <paper-icon-button slot="suffix" suffix id="clear" icon="clear" on-click="_clear"></paper-icon-button>
</paper-input>
```

It seems like maybe it is no longer possible to use suffix for this. Or might be a problem with paper-input. I will post more info once I figure out more.

**Comment by Zecat** [comment]
Looks like you hit https://github.com/PolymerElements/paper-input/issues/324.
You could eventually set `tabindex="-1"` on the icon button for Polymer 2 so the element is not focusable while the issue is open.

**Comment by jhuesos** [comment]
@Zecat I think is a good workaround. I will do that

**Comment by jhuesos** [comment]
Just pushed your suggestions to the branch. I close this for now
