### ISSUE TITLE
Release v3.0.0

### ISSUE THREAD

**Issue by goatandsheep** [ellipticaljs/paper-autocomplete#84]
I would like to use this package and am willing to help with whatever is necessary to bring this to the point where we can release [version 3.0.0](https://github.com/ellipticaljs/paper-autocomplete/releases/tag/3.0.0) onto the webcomponents store so I can use it. Let me know what is needed and if nothing else, we should release it as a major release.

**Comment by jhuesos** [comment]
Version 3.0.0 was released days ago. The reason why it does not appear in the webcomponents catalog I guess is because I made a mistake and the git tag I named it `3.0.0` and not `v3.0.0`. I just push the `v3.0.0`.

**Comment by jhuesos** [comment]
Since I just pushed the tag `v3.0.0`, I am not sure how long it will take to appear in the webcomponents.org. Do you know? Because once I pushed the new tag it should be automatically updated, isn't it?

In the meantime, you should be able to install version 3.0.0 with bower.

**Comment by jhuesos** [comment]
Version 3.0.0 appears now in webcomponents.org. Thanks for letting me know about this problem!
