### ISSUE TITLE
Dot in signal name cases listeners binding to fail

### ISSUE THREAD

**Issue by mutovkin** [ellipticaljs/paper-autocomplete#9]
I'm not really able to understand what's going on but here is as close description as I have.
I want to be able to listen to `autocomplete.change` event.  When I try to add the event via `listeners` object in the Polymer definition, I'm getting a strange error

> Uncaught TypeError: Invalid value used as weak map key

and no events arrive.

However, if I change line 407 in the paper-autocomplete.html to to send signal with dash instead of dot, and then update even registration - all works as expected and all events arrive correctly.

I've also tried to add lister inside ready() function like this:
`this.listen(this.$.airline, 'autocomplete.change', '_onAutocompleteChange');`

and this method of even binding also works well. Would love to know what is causing this weird behavior. I'm on Polymer 1.5.0 now.

**Comment by tachyon1337** [comment]
This appears to be an issue with Polymer.

https://github.com/Polymer/polymer/issues/1506 (last comment)

My understanding of the issue: Using an annotated event listener in polymer components to listen for custom events fired by another polymer component(using this.fire) throws an error if the event name contains a dot "."  The thrown error message is an invalid key in weak map. This despite Weak Map allowing arbitrary string values for keys.

Resolution: There's nothing to fix. Any resolution would be a work-around. The easiest work-around be to create a new public public property, eventNamespace, that would allow you to declaratively change the event name spacing scheme from "." to dash "-"

`<paper-autocomplete event-namespace="-"></paper-autocomplete>`

You can submit a pull request to implement the work around or you can wait for me to do it.

**Comment by tachyon1337** [comment]
I will update this myself at some point in the near future with a configurable public property to allow declaratively setting the event delimiter.

**Comment by tachyon1337** [comment]
manually merged in the change to allow setting the event delimiter via the component attribute
