### ISSUE TITLE
_handleSuggestions triggered on focus

### ISSUE THREAD

**Issue by M49A2** [ellipticaljs/paper-autocomplete#94]
As off 3.2.0 the _handleSuggestions is also executed when the field is focused. We would like this kind of behavior to be configurable (so we can turn it off) since we only want the suggestion logic to be executed on key strokes.

**Comment by jhuesos** [comment]
You are right. I thought this would be the behavior that everyone would
want but I guess I was wrong. I will make the new feature optional. Sorry
about that

**Comment by jhuesos** [comment]
Again, sorry for this change.

I just released `v3.3.0` that reverts the default behavior to do not display suggestions on focus. In order to get that behavior, you must add the option `show-results-on-focus`

**Comment by M49A2** [comment]
Cool! Thx for the quick response.

Regards.
Ruud
